package db

// postgresTableQueries is deliberately kept separate from the MySQL/SQLite
// schema. PostgreSQL uses native identity columns and positional $n params.
var postgresTableQueries = []string{
	`CREATE TABLE IF NOT EXISTS visits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ip TEXT, path TEXT, user_agent TEXT, referer TEXT,
        country TEXT, region TEXT, city TEXT,
        visit_count BIGINT NOT NULL DEFAULT 1,
        aggregate_key TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
	`CREATE TABLE IF NOT EXISTS downloads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_name TEXT, launcher TEXT, version TEXT, ip TEXT, country TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
	`CREATE TABLE IF NOT EXISTS ip_blacklist (
        ip TEXT PRIMARY KEY, reason TEXT,
        source TEXT NOT NULL DEFAULT 'manual',
        ban_type TEXT NOT NULL DEFAULT 'manual',
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
	`CREATE TABLE IF NOT EXISTS ip_daily_traffic (
        ip TEXT NOT NULL, date TEXT NOT NULL,
        bytes_downloaded BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (ip, date)
    )`,
	`CREATE TABLE IF NOT EXISTS daily_traffic (
        date TEXT PRIMARY KEY, bytes_downloaded BIGINT NOT NULL DEFAULT 0
    )`,
	`CREATE TABLE IF NOT EXISTS daily_completed_traffic (
        date TEXT PRIMARY KEY, bytes_downloaded BIGINT NOT NULL DEFAULT 0
    )`,
	`CREATE TABLE IF NOT EXISTS download_authorizations (
        authorization_id TEXT PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE,
        file_path TEXT NOT NULL, return_url TEXT, source TEXT, flow TEXT,
        client_ip TEXT, source_kind TEXT,
        status TEXT NOT NULL DEFAULT 'issued', expires_at TIMESTAMP NOT NULL,
        max_bytes BIGINT, range_limit INTEGER, request_id TEXT,
        first_transfer_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        consumed_at TIMESTAMP
    )`,
	`CREATE TABLE IF NOT EXISTS download_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        authorization_id TEXT, file_path TEXT, file_name TEXT,
        launcher TEXT, version TEXT, client_ip TEXT, country TEXT,
        bytes_served BIGINT NOT NULL DEFAULT 0, completed INTEGER NOT NULL DEFAULT 0,
        event_count BIGINT NOT NULL DEFAULT 1,
        aggregate_key TEXT,
        status_code INTEGER, date TEXT, source TEXT, source_id BIGINT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (source, source_id)
    )`,
	`CREATE TABLE IF NOT EXISTS system_info (
        key TEXT PRIMARY KEY, value TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
	`CREATE TABLE IF NOT EXISTS stats_snapshot (
        id INTEGER PRIMARY KEY, data TEXT,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
	`CREATE INDEX IF NOT EXISTS idx_ip_daily_traffic_date ON ip_daily_traffic(date)`,
	`CREATE INDEX IF NOT EXISTS idx_visits_created_at ON visits(created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_visits_country ON visits(country)`,
	`CREATE INDEX IF NOT EXISTS idx_downloads_created_at ON downloads(created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_downloads_file_name ON downloads(file_name)`,
	`CREATE INDEX IF NOT EXISTS idx_downloads_launcher_version ON downloads(launcher, version)`,
	`CREATE INDEX IF NOT EXISTS idx_dlauthz_status_expires ON download_authorizations(status, expires_at)`,
	`CREATE INDEX IF NOT EXISTS idx_dlevents_ip_date ON download_events(client_ip, date)`,
	`CREATE INDEX IF NOT EXISTS idx_dlevents_date ON download_events(date)`,
	`CREATE INDEX IF NOT EXISTS idx_dlevents_launcher ON download_events(launcher)`,
}
